spring.application.name=subscription-manager
# H2 Console setup - allows you to view the database at http://localhost:8080/h2-console
spring.datasource.url=jdbc:h2:mem:insurancedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Show SQL in the console (Great for debugging during a live coding test)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatically create tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
